# Generated by Django 3.2.6 on 2021-08-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painting_name', models.CharField(max_length=150)),
                ('image1', models.ImageField(upload_to='media/')),
                ('image2', models.ImageField(blank=True, upload_to='media/')),
                ('image3', models.ImageField(blank=True, upload_to='media/')),
                ('image4', models.ImageField(blank=True, upload_to='media/')),
                ('image5', models.ImageField(blank=True, upload_to='media/')),
                ('image6', models.ImageField(blank=True, upload_to='media/')),
                ('image7', models.ImageField(blank=True, upload_to='media/')),
                ('image8', models.ImageField(blank=True, upload_to='media/')),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
