# Generated by Django 3.2.6 on 2021-08-13 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
