# Generated by Django 3.2.6 on 2021-08-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=11)),
                ('gender', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('date', models.DateTimeField(default=None)),
            ],
        ),
    ]
