# Generated by Django 3.2.6 on 2021-08-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile',
            field=models.ImageField(blank=True, upload_to='media/profile_pic/'),
        ),
    ]
