# Generated by Django 3.2.6 on 2021-08-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_commment_postcomment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='name',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
